# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RDWHolder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RDWHolder

  pod 'ObjectMapper', '~> 2.2'

  pod 'Alamofire', '~> 4.4'

  pod 'AlamofireObjectMapper', '~> 4.0'

  pod 'Firebase'
  pod 'Firebase/Messaging'
  
  pod 'BerTlv', '0.1.0'

end
